### ISSUE TITLE
Problems with Task Runner

### ISSUE THREAD

**Issue by techiebud** [johnpapa/pluralsight-vscode-samples#2]
In the *_TSPlay *_project, I was following along in the *_Transpiling Typescript *_video around 2:07 and could not get VS Code to recognize the tsc task.   When I imitated what you were doing, my version of VS Code gave the message "No task runner configured".     I was stumped when I did not see  the tsc as a task.    I eventually clicked on the Configure Task Runner and noticed it created a .vscode folder.  I copied the tasks.json to this folder and then saw 'tsc' as a configured task as shown in the video.   It appears this was changed in VSCode in v.0.8.0 (September 2015).   I think it would be helpful to rename the .settings folder to .vscode folder in the sample code to reflect this change.

**Comment by johnpapa** [comment]
ah - so due to the folder rename, it did not pick it up. yes, i will change that here.

feel free to log things like this here. or better yet, make a PR :)

**Comment by techiebud** [comment]
Thanks John!  I'll create a pull request next time.

FYI:   I really enjoy your teaching style as I have taken many of your courses on Pluralsight.

**Comment by johnpapa** [comment]
I just renamed it to .vscode in all of the samples. I'll have them add a callout about that.

glad you like the courses :)
